[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roots="0.0.8"
num="0.4.1"
ndarray = "0.15.6"
itertools = "0.12.0"
rayon = "1.8.0"